language: node_js
node_js:
- '9'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod

deploy:
  provider: firebase
  token:
    secure: lsAu+urEYffQKB1gx7Yo6xVLt4oGhy2fbfq7WMldn+onoEJ1ugQSDNULXQj2hGUrlaTGhqVRRuonEEI5wea7tkYCyUJKVMhIQEEed/gn/Ey+6CQXL0nnU5Jfsdjy1q796DlsE2EewoB/7cwSkqe8r0WNyWVO3W6uI83b0zwrpGOt+Fu3WgG6+Ou4hEDUrEIM2s6gC8T9bTRCQjH0tn5ZySeyaq+252HfehPPfMlHp5H233XyXHE5D7KX4A4uD+flZFIdW+6a9GYqLxajdxFgT4/IKxLp94HD8/rXYCeW3p5CObCR1EIUXwImokMJNzYbqZgz/OSNeGF6Fbgdr4pMmWPP+0G9tDaj+NRBfGmkKCx/zCVXQaIq4AOupfixi8rE6LjMhf1O+FZqOE8Wt/2YzFNL2QuVSPz4lXdZnCpVC3I5zyUMRnz+hyqzBO0tdG0JJWgwRtdmsk93WtRh8L9gmIFVOYaGVdg8Tp89/EKtZII/gxCRIVhwkAfe7gzaJFhzN+z7srtprICeJR2j3qTXy89RkuyIXgS8CWXqVQ1pQgD5iU82c2hmNUc/daKBwxkaZcAP1+oyw+ZbdCgeQOJoZgdW13VF5toxUh9z5ZH8okKmcssN/WpIFzqkxCXyeg2MRhsU38AwXlLT6nCTGLUTJD7k9MVbqwJiTpBoptpL/YU=
